# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <SPIChanges>
  "stat.rain.drought.extr",
  # <SPIChanges>
  "stat.rain.drought.mod",
  # <SPIChanges>
  "stat.rain.drought.sev",
  # <SPIChanges>
  "stat.rain.normal",
  NULL
))
